### ISSUE TITLE
1.18.2 compatibility?

### ISSUE THREAD

**Issue by skxrlxt** [Latokike/myth-origins#3]
Hey! Absolutely love this mod. On my smp we have 7 different origin mods but every member managed to end up picking one from Myth!

We're gonna be updating to 1.18.2 soon and was wondering if the 18.1 jar file can be reused? Or will we have to wait for an update. Thanks!

**Comment by latokike** [comment]
Sorry for the late reply, but yes, you are able to reuse the 1.18.1 jar file.
